### ISSUE TITLE
[USER] 개발자 소개 패이지 에러납니다.

### ISSUE THREAD

**Issue by junu126** [DSM-DMS/DMS-Front-V3#72]
개발자 소개 페이지에 존재하는 이미지를 개발자도구를 통해 뜯어본 결과,  이미지를 요청중인 url에서 오류가 나는 걸로 확인됩니다. 수정 바랍니다.

**Comment by wArrnp** [comment]
리뷰 감사하고 조만간 패치 올리도록 하겠습니다.
